version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn -w 1 elina.wsgi:application -b 0.0.0.0:8000"
    environment:      
      - ALPHAVANTAGE_API_TOKEN=${ALPHAVANTAGE_API_TOKEN} 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - .redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .dbdata:/var/lib/postgresql/data
      - .data:/data
  celery:
    restart: on-failure
    build: .
    command: bash -c "celery -A elina beat -l info --logfile=celery.beat.log --detach && celery -A elina worker -l info"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
      - redis
      - backend

