version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    environment:      
      - ALPHAVANTAGE_API_TOKEN=${ALPHAVANTAGE_API_TOKEN} 
    ports:
      - 8000:8000
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - .redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_DB: alpha
      POSTGRES_USER: alpha
      POSTGRES_PASSWORD: alpha
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - .dbdata:/var/lib/postgresql/data
      - .data:/data
