version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn -w 1 elina.wsgi:application -b 0.0.0.0:8000"
    env_file:
      - ./.env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - .redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  db:
    image: postgres:14.0
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test:  [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .dbdata:/var/lib/postgresql/data
      - .data:/data
  celery:
    restart: on-failure
    build: .
    command: bash -c "celery -A elina beat -l info --logfile=celery.beat.log --detach && celery -A elina worker -l info"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend

  nginx:
    build: ./nginx
    volumes:
      - ./static:/app/static
    ports:
      - 82:80
    depends_on:
      - backend
