# Generated by Django 3.2.9 on 2022-01-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=9)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('server_refreshed_date', models.DateTimeField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate BTC/USD',
                'verbose_name_plural': 'Exchange Rates BTC/USD',
            },
        ),
    ]
