# Generated by Django 3.2.9 on 2022-01-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='insert_date',
            new_name='fetch_date',
        ),
    ]
