# Generated by Django 3.2.9 on 2022-01-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_rename_insert_date_exchangerate_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='server_refreshed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
