name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    env:
        POSTGRES_DB: alpha
        POSTGRES_USER: alpha
        POSTGRES_PASSWORD: alpha
        ALPHAVANTAGE_API_TOKEN: ${{ secrets.ALPHAVANTAGE_API_TOKEN }}
        SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DEBUG: True
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
    services:
      postgres:
        image: postgres:14.0
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: alpha
          POSTGRES_USER: alpha
          POSTGRES_PASSWORD: alpha
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: pip3 install --user -r requirements.txt
    - name: Run the celery beat
      run: celery -A elina beat -l info --logfile=celery.beat.log --detach
    - name: Run the celery
      run: celery -A elina worker -l info --detach
    - name: Run the Tests
      run: |
        python3 manage.py migrate
        python3 manage.py test